### PR TITLE
Applied feature for asking permission before going to pick image from…

### PR DESCRIPTION
**Pull request by HarshPanchal18**
… Gallery

Improved code structure in order to make more readable

### CODE REVIEW

**Review by yogendra131994 — APPROVED** [review]
Great work @HarshPanchal18. Thank you for contributing to my project. Looking forward for more contributions.

**Comment by yogendra131994** [comment]
You can review the app and raise issues if found or you can suggest new features we can work upon

**Comment by HarshPanchal18** [comment]
How about the viewing registered user's profile by scanning the QR code dedicated to their profile?

**Comment by yogendra131994** [comment]
How did you discover this repository

**Comment by HarshPanchal18** [comment]
By searching for issues globally on the GitHub.

**Pull request merged**
